export const semanticTokens = {
  background: "var(--color-background)",
  surface: "var(--color-surface)",
  surfaceElevated: "var(--color-surface-elevated)",
  surfaceInset: "var(--color-surface-inset)",
  text: "var(--color-text)",
  textStrong: "var(--color-text-strong)",
  textMuted: "var(--color-text-muted)",
  textSubtle: "var(--color-text-subtle)",
  border: "var(--color-border)",
  borderStrong: "var(--color-border-strong)",
  borderAction: "var(--color-border-action)",
  primary: "var(--color-primary)",
  secondary: "var(--color-secondary)",
  success: "var(--color-success)",
  warning: "var(--color-warning)",
  error: "var(--color-error)",
  danger: "var(--color-danger)",
  info: "var(--color-info)",
  onPrimary: "var(--color-on-primary)",
  onSecondary: "var(--color-on-secondary)",
  onSuccess: "var(--color-on-success)",
  onWarning: "var(--color-on-warning)",
  onDanger: "var(--color-on-danger)",
  onInfo: "var(--color-on-info)",
  focus: "var(--color-focus)",
  overlay: "var(--color-overlay)",
} as const;
